// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkLookup.Models;

namespace ParkLookup.Solution.Migrations
{
    [DbContext(typeof(ParkLookupContext))]
    [Migration("20220819191349_reAddInitialAndSeedData")]
    partial class reAddInitialAndSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParkLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Feature")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Feature = "Deepest and Clearest lake in USA.",
                            Location = "Oregon",
                            Name = "Crater Lake",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 2,
                            Feature = "Lakes, hot springs, cincer cones, and lava beds.",
                            Location = "California",
                            Name = "Lassen Volcanic",
                            Type = "National Park"
                        },
                        new
                        {
                            ParkId = 3,
                            Feature = "Tallest peak in North America and over 6 million acres of wilderness.",
                            Location = "Alaska",
                            Name = "Denali",
                            Type = "National Park and Preserve"
                        },
                        new
                        {
                            ParkId = 4,
                            Feature = "Sweeping views and several thousand climbs, with over a thousand bolted routes.",
                            Location = "Oregon",
                            Name = "Smith Rock",
                            Type = "State Park"
                        },
                        new
                        {
                            ParkId = 5,
                            Feature = "Camp, fish, run, climb, bike, boat, ride horses, sail, and more at this lively recreational destination.",
                            Location = "Idaho",
                            Name = "Ponderosa",
                            Type = "State Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
